//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripId { get; set; }
        public int TrainId { get; set; }
        public System.DateTime TripDateTime { get; set; }
        public decimal Cost { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
